### ISSUE TITLE
Crash after start

### ISSUE THREAD

**Issue by stalkerg** [kvark/vange-rs#1]
Backtrace:

```bash
     Running `target/debug/road`
thread '<main>' panicked at 'arithmetic operation overflowed', src/splay.rs:58
stack backtrace:
   1:     0x5575c3222720 - std::sys::backtrace::tracing::imp::write::h4c73fcd3363076f5
   2:     0x5575c322531b - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h0422dbb3077e6747
   3:     0x5575c3224fa3 - std::panicking::default_hook::haac48fa641db8fa2
   4:     0x5575c321a5bf - std::sys_common::unwind::begin_unwind_inner::h39d40f52add53ef7
   5:     0x5575c321b4a8 - std::sys_common::unwind::begin_unwind_fmt::h64c0ff793199cc1b
   6:     0x5575c3221c01 - rust_begin_unwind
   7:     0x5575c325b7cf - core::panicking::panic_fmt::h73bf9d7e8e891a73
   8:     0x5575c325baa8 - core::panicking::panic::hdbcf9a6d5c170498
   9:     0x5575c2f7f98b - road::splay::Splay::expand1::_$u7b$$u7b$closure$u7d$$u7d$::h1028cbb8d13777f5
                        at src/splay.rs:58
  10:     0x5575c2f7f3bf - road::splay::Splay::decompress::hac91f6bd5aaeb46f
                        at src/splay.rs:44
  11:     0x5575c2f7f087 - road::splay::Splay::expand1::h37b2d84b8bc810ab
                        at src/splay.rs:58
  12:     0x5575c2f2dc79 - road::level::load::hec1ee9db2212ee9c
                        at src/level.rs:89
  13:     0x5575c2f1fb8b - road::main::hb0c82faee450c80f
                        at src/main.rs:59
  14:     0x5575c3224be4 - std::sys_common::unwind::try::try_fn::h09ba69fd13531e58
  15:     0x5575c3221b8b - __rust_try
  16:     0x5575c322462b - std::rt::lang_start::h5b0863080165c75e
  17:     0x5575c2f56039 - main
  18:     0x7fb1e05ca71f - __libc_start_main
  19:     0x5575c2f18888 - _start
  20:                0x0 - <unknown>
error: Process didn't exit successfully: `target/debug/road` (exit code: 101)

```

**Comment by stalkerg** [comment]
last_char = fun(last_char, tree_char[c_index]); -- |b, c| b+c

last_char = 139
tree_char[c_index] = 254
and last_char is u8....

**Comment by kvark** [comment]
Interesting, why do I not get this? Are you loading `fostral` or some other level?

**Comment by stalkerg** [comment]
I changed only path to dir.
