### ISSUE TITLE
Failed to execute glslangValidator - No such file or directory

### ISSUE THREAD

**Issue by rofrol** [kvark/vange-rs#108]
In `config/settings.ron`:

```
data_path: "/home/roman/.steam/steam/steamapps/common/Vangers/data",
```

```bash
~/personal_projects/rust/vendor/vange-rs (master %)$ RUST_BACKTRACE=1 cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `target/debug/road`
thread 'main' panicked at 'Failed to execute glslangValidator: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1165:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
  12: rust_begin_unwind
             at src/libstd/panicking.rs:302
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:139
  14: core::result::unwrap_failed
             at src/libcore/result.rs:1165
  15: core::result::Result<T,E>::expect
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/result.rs:960
  16: glsl_to_spirv::compile_inner
             at /home/roman/.cargo/registry/src/github.com-1ecc6299db9ec823/glsl-to-spirv-0.1.7/src/lib.rs:53
  17: glsl_to_spirv::compile
             at /home/roman/.cargo/registry/src/github.com-1ecc6299db9ec823/glsl-to-spirv-0.1.7/src/lib.rs:19
  18: vangers::render::Shaders::new
             at src/render/mod.rs:172
  19: vangers::render::object::Context::create_pipeline
             at src/render/object.rs:122
  20: vangers::render::object::Context::new
             at src/render/object.rs:318
  21: vangers::render::Render::new
             at src/render/mod.rs:456
  22: road::game::Game::new
             at bin/road/game.rs:344
  23: road::main
             at bin/road/main.rs:28
  24: std::rt::lang_start::{{closure}}
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  25: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:48
  26: std::panicking::try::do_call
             at src/libstd/panicking.rs:287
  27: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  28: std::panicking::try
             at src/libstd/panicking.rs:265
  29: std::panic::catch_unwind
             at src/libstd/panic.rs:396
  30: std::rt::lang_start_internal
             at src/libstd/rt.rs:47
  31: std::rt::lang_start
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  32: main
  33: __libc_start_main
  34: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by kvark** [comment]
Interesting, thanks for the report! glslValidator is supposed to be provided by `glsl_to_spirv` crate. It looks for it in the build folder at run-time (which is annoying to package...). I've been running it on many many systems and haven't seen this happening.

**Comment by MatusT** [comment]
I get the same error on my project here https://github.com/MatusT/vis2-molecules.

```
thread 'main' panicked at 'Failed to execute glslangValidator: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', C:\Users\matus\.cargo\registry\src\github.com-1ecc6299db9ec823\glsl-to-spirv-0.1.7\src\lib.rs:53:18
```

Seems like wgpu-rs hardcodes path to glsl-to-spirv? I guess this should be moved to wgpu(-rs)/glsl_tospirv issues.

**Comment by kvark** [comment]
@MatusT it's not wgpu-rs. It doesn't depend or include glsl-to-spirv in any way.
