### ISSUE TITLE
Enabling `game.physics.gpu_collision` causes a segfault

### ISSUE THREAD

**Issue by suhr** [kvark/vange-rs#120]
```
Thread 1 "road" received signal SIGSEGV, Segmentation fault.
0x00005555557b4f29 in core::task::poll::Poll<T>::map ()
(gdb) bt
#0  0x00005555557b4f29 in core::task::poll::Poll<T>::map ()
#1  0x000055555595d005 in futures_util::stream::stream::StreamExt::poll_next_unpin ()
#2  0x000055555595c41a in futures_executor::local_pool::LocalPool::poll_pool_once ()
#3  0x000055555595c072 in std::thread::local::LocalKey<T>::with ()
#4  0x000055555595c2cb in futures_executor::local_pool::LocalPool::run_until_stalled ()
#5  0x00005555556134c1 in road::boilerplate::Harness::main_loop::{{closure}} ()
#6  0x00005555555d2125 in winit::platform_impl::platform::x11::EventLoop<T>::run ()
#7  0x0000555555611166 in winit::platform_impl::platform::EventLoop<T>::run ()
#8  0x0000555555611102 in winit::event_loop::EventLoop<T>::run ()
#9  0x000055555561341b in road::boilerplate::Harness::main_loop ()
#10 0x00005555555ed301 in road::main ()
#11 0x000055555560af03 in std::rt::lang_start::{{closure}} ()
#12 0x00005555559725b3 in std::rt::lang_start_internal::{{closure}} () at src/libstd/rt.rs:52
#13 std::panicking::try::do_call () at src/libstd/panicking.rs:348
#14 std::panicking::try () at src/libstd/panicking.rs:325
#15 std::panic::catch_unwind () at src/libstd/panic.rs:394
#16 std::rt::lang_start_internal () at src/libstd/rt.rs:51
#17 0x00005555555ed562 in main ()
```

**Comment by kvark** [comment]
Thank you for filing! I haven't tested this code path with latest changes lately.
